name: neolua
version: 1.0.0
github: "nvim-neorocks/neorocks"
license: GPL-2
author: "Marc Jakobi"
maintainer: "mrcjkb89@outlook.com"
copyright: "Copyright (c) 2023 Marc Jakobi"
category: CLI
synopsis: A CLI adapter to map Lua's CLI to Neovim's CLI for lua interpretation.

dependencies:
- base >= 4.7 && < 5

executables:
    neolua:
      source-dirs: src
      main: NeoLua.hs
      dependencies:
        - optparse-applicative
        - text
        - process
      ghc-options:
        - -main-is NeoLua
