name: "Nix build"
on:
  pull_request:
  push:
jobs:
  checks:
    runs-on: ubuntu-latest
    name: Nix checks
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: mrcjkb
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L

  build:
    needs: checks
    name: ${{ matrix.attribute }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        attribute:
          - .#neorocks
          - .#devShells.x86_64-linux.default
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - run: nix build --accept-flake-config "${{matrix.attribute}}" -L

  tests:
    needs: build
    runs-on: ubuntu-latest
    name: Integration test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: mrcjkb
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run integration tests
        run: |
          nix profile install --accept-flake-config ".#neorocks"
          cd testproject
          luarocks init
          luarocks config --scope project lua_interpreter neorocks
          luarocks test
          rm -r lua_modules/ .luarocks/ luarocks
          luarocks init
          luarocks config --scope project lua_interpreter neorocks-nightly
          luarocks test
        shell: bash
